<?php

namespace ContainerEnNgYHF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gcg7rU_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gcg7rU.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gcg7rU.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::add' => ['privates', '.service_locator.VTbrDAj', 'get_ServiceLocator_VTbrDAjService', true],
            'App\\Controller\\CommentController::changeState' => ['privates', '.service_locator.MvdbDJM', 'get_ServiceLocator_MvdbDJMService', true],
            'App\\Controller\\CommentController::index' => ['privates', '.service_locator.Il9hjn7', 'get_ServiceLocator_Il9hjn7Service', true],
            'App\\Controller\\IndexController::comment' => ['privates', '.service_locator.U6J5bau', 'get_ServiceLocator_U6J5bauService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.UyfBVNw', 'get_ServiceLocator_UyfBVNwService', true],
            'App\\Controller\\LessonController::add' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\LessonController::delete' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController::edit' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController::getForm' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController::index' => ['privates', '.service_locator.UyfBVNw', 'get_ServiceLocator_UyfBVNwService', true],
            'App\\Controller\\LessonController::saveForm' => ['privates', '.service_locator._80eMBn', 'get_ServiceLocator_80eMBnService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CommentController:add' => ['privates', '.service_locator.VTbrDAj', 'get_ServiceLocator_VTbrDAjService', true],
            'App\\Controller\\CommentController:changeState' => ['privates', '.service_locator.MvdbDJM', 'get_ServiceLocator_MvdbDJMService', true],
            'App\\Controller\\CommentController:index' => ['privates', '.service_locator.Il9hjn7', 'get_ServiceLocator_Il9hjn7Service', true],
            'App\\Controller\\IndexController:comment' => ['privates', '.service_locator.U6J5bau', 'get_ServiceLocator_U6J5bauService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.UyfBVNw', 'get_ServiceLocator_UyfBVNwService', true],
            'App\\Controller\\LessonController:add' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\LessonController:delete' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController:edit' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController:getForm' => ['privates', '.service_locator.svtVaCr', 'get_ServiceLocator_SvtVaCrService', true],
            'App\\Controller\\LessonController:index' => ['privates', '.service_locator.UyfBVNw', 'get_ServiceLocator_UyfBVNwService', true],
            'App\\Controller\\LessonController:saveForm' => ['privates', '.service_locator._80eMBn', 'get_ServiceLocator_80eMBnService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CommentController::add' => '?',
            'App\\Controller\\CommentController::changeState' => '?',
            'App\\Controller\\CommentController::index' => '?',
            'App\\Controller\\IndexController::comment' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\LessonController::add' => '?',
            'App\\Controller\\LessonController::delete' => '?',
            'App\\Controller\\LessonController::edit' => '?',
            'App\\Controller\\LessonController::getForm' => '?',
            'App\\Controller\\LessonController::index' => '?',
            'App\\Controller\\LessonController::saveForm' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommentController:add' => '?',
            'App\\Controller\\CommentController:changeState' => '?',
            'App\\Controller\\CommentController:index' => '?',
            'App\\Controller\\IndexController:comment' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\LessonController:add' => '?',
            'App\\Controller\\LessonController:delete' => '?',
            'App\\Controller\\LessonController:edit' => '?',
            'App\\Controller\\LessonController:getForm' => '?',
            'App\\Controller\\LessonController:index' => '?',
            'App\\Controller\\LessonController:saveForm' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
