<?php

namespace ContainerEnNgYHF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6J5bauService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U6J5bau' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U6J5bau'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lesson' => ['privates', '.errored..service_locator.U6J5bau.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.U6J5bau": it references class "App\\Entity\\Lesson" but no such service exists.'],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
            'paginator' => '?',
        ]);
    }
}
