<?php

namespace ContainerEnNgYHF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MvdbDJMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MvdbDJM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MvdbDJM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.MvdbDJM.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.MvdbDJM": it references class "App\\Entity\\Comment" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'entityManager' => '?',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
