<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Il9hjn7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Il9hjn7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Il9hjn7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'lesson' => ['privates', '.errored..service_locator.Il9hjn7.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.Il9hjn7": it references class "App\\Entity\\Lesson" but no such service exists.'],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
