<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_80eMBnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._80eMBn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._80eMBn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'form' => ['privates', '.errored..service_locator._80eMBn.Symfony\\Component\\Form\\FormInterface', NULL, 'Cannot autowire service ".service_locator._80eMBn": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'form' => 'Symfony\\Component\\Form\\FormInterface',
        ]);
    }
}
