<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UyfBVNwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UyfBVNw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UyfBVNw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
