<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VTbrDAjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VTbrDAj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VTbrDAj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lesson' => ['privates', '.errored..service_locator.VTbrDAj.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.VTbrDAj": it references class "App\\Entity\\Lesson" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'lesson' => 'App\\Entity\\Lesson',
        ]);
    }
}
