<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._80eMBn.Symfony\Component\Form\FormInterface' shared service.
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._80eMBn": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
