<?php

namespace ContainerF6F5sFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLesson4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.svtVaCr.App\Entity\Lesson' shared service.
     *
     * @return \App\Entity\Lesson
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.svtVaCr": it references class "App\\Entity\\Lesson" but no such service exists.');
    }
}
