<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnNgYHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnNgYHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnNgYHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnNgYHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnNgYHF\App_KernelDevDebugContainer([
    'container.build_hash' => 'EnNgYHF',
    'container.build_id' => 'ec4ab0dd',
    'container.build_time' => 1606384961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnNgYHF');
